version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: frontend
#    env_file:
#      - .env
    environment:
      - BACKEND_URL=http://backend:88/roast  # Use service name instead of static IP
    ports:
      - "89:89"
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: backend
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - .env
#    environment:
#      - BACKEND_URL=http://backend:88/roast
    ports:
      - "88:88"  # Expose backend port
    networks:
      - my-network

#   Jenkins service (commented out for now, can be enabled later)
  jenkins:
     image: jenkins/jenkins:latest
     user: root
     ports:
       - "${JENKINS_PORT}:8080"
     env_file:
       - .env
     networks:
       - my-network
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - jenkins-data:/var/jenkins_home

  tests:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: tests
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  jenkins-data:
