services:

  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: frontend
    env_file:
      - .env
    ports:
      - "89:89"
    networks:
      my-network:
        ipv4_address: ${FRONTEND_IP}

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: backend
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "88:88"
    env_file:
      - .env
    networks:
      my-network:
        ipv4_address: ${BACKEND_IP}

  jenkins:
    image: jenkins/jenkins:latest
    user: root
    ports:
      - "${JENKINS_PORT}:8080"
    env_file:
      - .env
    networks:
      my-network:
        ipv4_address: ${JENKINS_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home


networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_IP}


volumes:
  jenkins-data: