version: '3.8'
services:

  ai-server:
    build:
      context: .
      dockerfile: /bot/Dockerfile
      args:
        AI_PORT: ${AI_PORT}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        HOST: ${HOST}

    ports:
      - ${AI_PORT}:${AI_PORT}
    env_file:
      - .env
    networks:
      my-network:
        ipv4_address: 192.168.1.100
    restart: on-failure

  app-server:
    build:
      context: .
      dockerfile: /app/Dockerfile
      args:
        APP_PORT: ${APP_PORT}
        HOST: ${HOST}

    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      my-network:
        ipv4_address: 192.168.1.101
    restart: on-failure

  tests:
    build:
      context: .
      dockerfile: /tests/Dockerfile
    env_file:
      - .env

    networks:
      my-network:
        ipv4_address: 192.168.1.102
    volumes:
      - ./test_logs:/tests/logs

  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - ${JENKINS_PORT}:8080
    env_file:
      - .env
    container_name: jenkins
    volumes:
      - "/home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      my-network:



  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    env_file:
      - .env
    ports:
      - ${SONARQUBE_PORT}:9000
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      my-network:
        ipv4_address: 192.168.1.104

  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      my-network:
        ipv4_address: 192.168.1.105

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data: