kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: OPENAI_API_KEY
          image: medvijenia/app-backend:latest
          name: backend
          ports:
            - containerPort: 88
              protocol: TCP
      restartPolicy: Always

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: medvijenia/app-frontend:latest
          name: frontend
          ports:
            - containerPort: 89
              protocol: TCP
      restartPolicy: Always
