apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-backend
  labels:
    app: ai-agent-backend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ai-agent-backend
  template:
    metadata:
      labels:
        app: ai-agent-backend
    spec:
      containers:
      - name: ai-agent-backend
        image: medvijenia/simple-frontend:1.0
        ports:
        - containerPort: 88
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: OPENAI_API_KEY
        readinessProbe:
          httpGet:
            path: /health
            port: 88
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 88
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-backend-service
spec:
  selector:
    app: ai-agent-backend
  ports:
    - protocol: TCP
      port: 88
      targetPort: 88
  type: ClusterIP
