kind: Secret
apiVersion: v1
metadata:
  name: secret
type: Opaque
data:
  OPENAI_API_KEY: c2stV2pOYUVINGtoM1lnNFRveUdNY2Q4VW45eU1VSHF5WGl1Y2RKTHhkVXg2VDNCbGJrRkpNeExHM19DaTRFeUkxTmxlUktNTUVfU2VoUEJBNDNYam9zUTh3YmIyd0E=
