kind: Service
apiVersion: v1
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "89"
      port: 89
      targetPort: 89
  selector:
    io.kompose.service: frontend

---

kind: Service
apiVersion: v1
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "88"
      port: 88
      targetPort: 88
  selector:
    io.kompose.service: backend
