# cd /infra
# helm install app /k8s -f k8s/values.yaml

replicaCount: 10

logging:
  enabled: true

ingress:
  enabled: true

daemonset:
  enabled: true

image:
  frontend: medvijenia/app-frontend
  backend: medvijenia/app-backend