apiVersion: v2
appName: my-app
version: 1.0.0
namespace: default
description: A Helm chart for deploying a Flask application with best practices

maintainers:
  - name: DevOps Team

replicaCount: 3

logging:
  enabled: true
