# cd /infra
# helm install app /k8s -f k8s/values.yaml
NAMESPACE: default
APP_NAME: devops

replicaCount: 5

logging:
  enabled: true

ingress:
  enabled: true

daemonset:
  enabled: true

image:
  frontend: medvijenia/app-frontend:latest
  backend: medvijenia/app-backend:latest