# cd /infra
# helm install app /k8s -f k8s/values.yaml
NAMESPACE: k8s
replicaCount: 5

logging:
  enabled: true

ingress:
  enabled: true

daemonset:
  enabled: true

image:
  frontend: medvijenia/app-frontend
  backend: medvijenia/app-backend