node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    def scannerHome = tool 'SonarScanner';
    withSonarQubeEnv() {
      sh "${scannerHome}/bin/sonar-scanner"
    }
  }
}







// pipeline {
//
//     agent any
//
//     environment {
//         SCANNER_HOME = tool 'sonar-scanner'
//     }
//
//     stages {
//
//         stage('Checkout') {
//             steps {
//                 echo 'Checking out the repository...'
//                 git branch: 'main', url: 'https://github.com/MedviJenka/roast-bot.git'
//             }
//         }
//
//         stage("Sonarqube Analysis") {
//             steps {
//                 withSonarQubeEnv('sonar-scanner') {
//                     sh '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=app \
//                     -Dsonar.projectKey=app'''
//                 }
//             }
//         }
//
//         stage("quality gate") {
//             steps {
//                 script {
//                     waitForQualityGate abortPipeline: false, credentialsId: 'SONAR_TOKEN'
//                 }
//             }
//         }
//     }
// }
//
//
//
