apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
      - name: ai-server
        image: ai-server-image
        ports:
        - containerPort: ${AI_PORT}
        envFrom:
        - configMapRef:
            name: ai-server-config
        readinessProbe:
          httpGet:
            path: /health
            port: ${AI_PORT}
          initialDelaySeconds: 10
          periodSeconds: 30
