apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
  labels:
    app: app-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: app-server
        image: app-server:latest
        ports:
        - containerPort: ${APP_PORT}
        envFrom:
        - secretRef:
            name: ${OPENAI_API_KEY}
