apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Values.appName }}
    meta.helm.sh/release-namespace: default
