kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Values.appName }}
    meta.helm.sh/release-namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          ports:
            - containerPort: 88

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Values.appName }}
    meta.helm.sh/release-namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: medvijenia/app-frontend:latest
          name: frontend
          ports:
            - containerPort: 89
              protocol: TCP
      restartPolicy: Always
