kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: {{ .Values.NAMESPACE }}
  selector:
    matchLabels:
      app: backend

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          ports:
            - containerPort: 88
          env:
            - name: BACKEND_URL
              value: "http://backend:88/roast"

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  selector:
    matchLabels:
      app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: {{ .Values.image.frontend }}
          name: frontend
          ports:
            - containerPort: 89
              protocol: TCP
      restartPolicy: Always
