kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.NAMESPACE }}
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 89
      targetPort: 88
      protocol: TCP
  selector:
    service: frontend

---

kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 88
      protocol: TCP
  selector:
    service: backend