pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the latest code from your repository
                git branch: 'main', url: 'https://github.com/MedviJenka/devsecops-final-project.git'
            }
        }
        stage('Build') {
            steps {
                // Build your application using docker-compose
                sh 'docker-compose build'
            }
        }
        stage('Deploy') {
            steps {
                // Optionally, bring up the containers (or deploy in your preferred way)
                sh 'docker-compose up -d'
            }
        }
    }
}
